cutoff: 5.0
num_layers: 4
hidden_channels: 256
out_channels: 128
int_emb_size: 64
basis_emb_size_dist: 8
basis_emb_size_angle: 8
basis_emb_size_torsion: 8
out_emb_channels: 128
num_spherical: 7
num_radial: 6
envelope_exponent: 5
num_before_skip: 1
num_after_skip: 2
num_output_layers: 1
output_init: 'GlorotOrthogonal'
use_node_features: True